gateway:
  addr: ":8888"

consul:
  addr: "127.0.0.1"
  port: ""
  token: ""
  scheme: ""
  timeout: ""

zipkin:
  url: "http://zipkin:9411/api/v2/spans"
  servicename: gateway_service
  samplerate: 1.0

jwt:
  secret: "abc"
